# Generated by Django 4.2.7 on 2024-07-08 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(choices=[('AAPL', 'Apple Inc.'), ('MSFT', 'Microsoft Corporation'), ('AMZN', 'Amazon.com Inc.'), ('GOOGL', 'Alphabet Inc.'), ('TSLA', 'Tesla, Inc.'), ('META', 'Meta Platforms, Inc.'), ('NVDA', 'NVIDIA Corporation'), ('KO', 'Coca-Cola Company'), ('INTC', 'Intel Corporation'), ('V', 'Visa Inc.')], max_length=10, unique=True)),
                ('price', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
