# Generated by Django 4.2.7 on 2024-07-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_user',
            name='money',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=10),
        ),
    ]
