# Generated by Django 4.2.7 on 2024-07-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_stock_user_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_user',
            name='current_and_yesterday_money',
            field=models.JSONField(default=list),
        ),
    ]
