# Generated by Django 4.2.7 on 2024-07-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_stock_user_current_and_yesterday_money'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock_user',
            name='current_and_yesterday_money',
        ),
        migrations.AddField(
            model_name='stock_user',
            name='count_for_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock_user',
            name='today_money',
            field=models.IntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='stock_user',
            name='yesterday_money',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
