# Generated by Django 4.2.7 on 2024-07-08 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userstock_alter_stock_price_delete_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(choices=[('AAPL', 'Apple Inc.'), ('MSFT', 'Microsoft Corporation'), ('AMZN', 'Amazon.com Inc.'), ('GOOGL', 'Alphabet Inc.'), ('TSLA', 'Tesla, Inc.'), ('META', 'Meta Platforms, Inc.'), ('NVDA', 'NVIDIA Corporation'), ('KO', 'Coca-Cola Company'), ('INTC', 'Intel Corporation'), ('V', 'Visa Inc.')], max_length=10),
        ),
    ]
