# Generated by Django 4.2.7 on 2024-07-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_stock_user_count_for_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_user',
            name='today_money',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stock_user',
            name='yesterday_money',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
