# Generated by Django 4.2.7 on 2024-07-08 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_stock_symbol'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userstock',
            unique_together=set(),
        ),
    ]
